import Settings from "../Settings";

interface TranslationProps {
    it: string
} 

const availableTranslations = new Map<string, TranslationProps>([
    ["Album art", {it: "Copertina dell'album"}],
    ["Enable/disable shuffle", {it: "Abilita/disabilita riproduzione casuale"}],
    ["Play/pause", {it: "Riproduci/metti in pausa"}],
    ["Next track", {it: "Prossima traccia"}],
    ["Toggle between loop options", {it: "Cambia tra le opzioni di ripetizione"}],
    ["Show/hide lyrics", {it: "Mostra/nascondi testo"}],
    ["Show/hide queue", {it: "Mostra/nascondi coda"}],
    ["Enable/disable sleep timer", {it: "Abilita/disabilita timer pausa"}],
    ["Sync text to timestamp", {it: "Sincronizza testo alla riproduzione"}],
    ["Previous track", {it: "Traccia precedente"}],
    ["No track is being played", {it: "Nessuna traccia è in riproduzione"}],
    ["Track information will appear here", {it: "Le informazioni sulla traccia appariranno qui"}],
    ["Queue", {it: "Coda"}],
    ["Added by the user", {it: "Aggiunto dall'utente"}],
    ["Playing next", {it: "In coda"}],
    ["Sleep timer", {it: "Timer pausa"}],
    ["Timer running", {it: "Timer in esecuzione"}],
    ["Hours", {it: "Ore"}],
    ["Minutes", {it: "Minuti"}],
    ["Seconds", {it: "Secondi"}],
    ["Wait the end of the song before pausing the track", {it: "Attendi la fine della canzone prima di mettere in pausa la traccia"}],
    ["Close", {it: "Chiudi"}],
    ["Disable", {it: "Disabilita"}],
    ["Start", {it: "Avvia"}],
    ["hour", {it: "ora"}],
    ["hours", {it: "ore"}],
    ["minute", {it: "minuto"}],
    ["minutes", {it: "minuti"}],
    ["seconds", {it: "secondi"}],
    ["second", {it: "secondo"}],
    ["remaining", {it: "rimanenti"}],
    ["Playback will be paused at the end of this song", {it: "La riproduzione verrà messa in pausa alla fine di questa canzone."}],
    ["Close settings dialog", {it: "Chiudi dialogo delle impostazioni"}],
    ["Settings", {it: "Impostazioni"}],
    ["Lyrics integration", {it: "Integrazione coi testi"}],
    ["The application can automatically fetch missing lyrics from", {it: "L'applicazione può automaticamente ottenere i testi mancanti da"}],
    ["The application will only share the necessary metadata to identify the currently-playing song. If you enable this, you're also subject to LRCLib's Terms of Service", {it: "L'applicazione condividerà solamente i metadati necessari per identificare la canzone in riproduzione. Se abiliti questo, accetti i termini di servizio di LRCLib"}],
    ["Automatically fetch lyrics if missing", {it: "Ottieni automaticamente i testi se mancanti"}],
    ["Automatically fetch lyrics if the uploaded ones aren't synced", {it: "Ottieni automaticamente i testi se quelli forniti non sono sincronizzati"}],
    ["Browser buttons behavior", {it: "Comportamento dei pulsanti nel browser"}],
    ["You can control the behavior of the media buttons you can find in the Control Center while playing music", {it: "Puoi controllare il comportamento dei pulsanti multimediali che puoi trovare nel Centro di Controllo mentre ascolti la musica"}],
    ["When clicking on the next/previous song button", {it: "Quando clicchi sul pulsante per la prossima/precedente canzone"}],
    ["Skip to the next/previous track", {it: "Passa alla prossima/precedente canzone"}],
    ["Go forwards/backwards in the track", {it: "Vai più avanti/indietro nella traccia"}],
    ["When clicking on the go forwards/backwards button", {it: "Quando clicchi sul pulsante per andare avanti/indietro nella traccia"}],
    ["When using the go forwards/backwards button, always skip of", {it: "Quando usi il pulsante per andare avanti/indietro nella traccia, salta sempre"}],
    ["Application theme", {it: "Tema dell'applicazione"}],
    ["Here you can change all the colors and values used by the application. You can also customize the font and the CSS blur styling. Note that, if the font you've put doesn't load, you might need to disable your browser's privacy protection. The sliders below the color inputs permit to change the opacity of the property", {it: "Qui puoi cambiare tutti i colori ed i valori utilizzati dall'applicazione. Puoi anche personalizzare il font ed il codice CSS della sfumatura. Nota che, se il font che hai messo non carica, potresti dover disattivare le protezioni per la privacy del tuo browser. Gli slider in basso ai selettori colore permettono di regolare l'opacità della proprietà"}],
    ["Background color", {it: "Colore di sfondo"}],
    ["Text/icon color", {it: "Colore del testo/icone"}],
    ["Secondary text color", {it: "Colore del testo secondario"}],
    ["Previous lyrics color (for word-by-word lyrics)", {it: "Colore del testo precedente (per i testi parola-per-parola)"}],
    ["Main card color", {it: "Colore della card principale"}],
    ["Secondary card color", {it: "Colore della card secondaria"}],
    ["Accent color", {it: "Colore accent"}],
    ["Color around the album art", {it: "Colore attorno alla copertina dell'album"}],
    ["CSS font name", {it: "Nome del font CSS"}],
    ["CSS filter for the background album art", {it: "Filtro CSS per la copertina di sfondo"}],
    ["CSS filter for the box-shadow around album arts", {it: "Filtro CSS per la box-shadow attorno alla copertina dell'album"}],
    ["Application size", {it: "Peso dell'applicazione"}],
    ["The application is using", {it: "L'applicazione sta usando"}],
    ["If you're running low on memory, you can use the following buttons to save space. Note that the website will automatically refresh at the end of the process", {it: "Se hai quasi esaurito lo spazio, puoi usare i seguenti pulsanti per salvare spazio. Nota che il sito si aggionerà automaticamente alla fine del processo"}],
    ["Delete all album arts", {it: "Elimina tutte le copertine dell'album"}],
    ["Delete all artist images", {it: "Elimina tutte le immagini degli artisti"}],
    ["Delete all playlist images", {it: "Elimina tutte le immagini delle playlist"}],
    ["Delete all song stats", {it: "Elimina tutte le statistiche sulle canzoni"}],
    ["Delete everything", {it: "Elimina tutto"}],
    ["Close stats dialog", {it: "Chiudi dialogo delle statistiche"}],
    ["Stats about", {it: "Statistiche su"}],
    ["You've listened to", {it: "Hai ascoltato a"}],
    ["aproximately", {it: "approssimatamente"}],
    ["time", {it: "volta"}],
    ["times", {it: "volte"}],
    ["for a total of", {it: "per un totale di"}],
    ["and", {it: "e"}],
    ["When you've listened to", {it: "Quando hai ascoltato"}],
    ["Show the", {it: "Mostra"}],
    ["hours of the day", {it: "le ore del giorno"}],
    ["days of the week", {it: "i giorni della settimana"}],
    ["days of the month", {it: "i giorni del mese"}],
    ["months of the year", {it: "i mesi dell'anno"}],
    ["years", {it: "gli anni"}],
    ["Chart type", {it: "Tipo di grafico"}],
    ["Bar", {it: "Barre"}],
    ["Doughnut", {it: "Ciambella"}],
    ["Line", {it: "Linea"}],
    ["Polar area", {it: "Area polare"}],
    ["Show empty columns", {it: "Mostra le colonne vuote"}],
    ["Data unit: seconds", {it: "Unità dei dati: secondi"}],
    ["Download chart", {it: "Scarica grafico"}],
    ["Export stats", {it: "Esporta statistiche"}],
    ["Expand item", {it: "Espandi elemento"}],
    ["Options about this specific track", {it: "Opzioni su questa specifica traccia"}],
    ["Add to queue", {it: "Aggiungi alla coda"}],
    ["Add to playlist", {it: "Aggiungi alla playlist"}],
    ["Create new playlist", {it: "Crea una nuova playlist"}],
    ["Remove from playlist", {it: "Rimuovi dalla playlist"}],
    ["Delete track", {it: "Elimina traccia"}],
    ["Edit metadata", {it: "Modifica metadati"}],
    ["View stats", {it: "Visualizza statistiche"}],
    ["Pick a name for the new playlist.", {it: "Scegli un nome per la nuova playlist"}],
    ["Text options", {it: "Opzioni del testo"}],
    ["Text", {it: "Testo"}],
    ["Font size", {it: "Dimensione del font"}],
    ["Font used", {it: "Font utilizzato"}],
    ["Background color", {it: "Colore di sfondo"}],
    ["Text color", {it: "Colore del testo"}],
    ["Click here to upload a custom picture", {it: "Clicca qui per caricare un'immagine personalizzata"}],
    ["Save edits", {it: "Salva modifiche"}],
    ["Close without saving", {it: "Chiudi senza salvare"}],
    ["Edit the metadata of", {it: "Modifica i metadati di"}],
    ["Album art options", {it: "Opzioni sulla copertina"}],
    ["Click on the album art to upload a custom image, or change the default text with the options below", {it: "Clicca sulla copertina per caricare un'immagine personalizzata, oppure cambia il testo di default con le opzioni in basso"}],
    ["Other album information", {it: "Altre informazioni sull'album"}],
    ["Album name", {it: "Nome dell'album"}],
    ["Album artists", {it: "Artisti dell'album"}],
    ["Album artists (sort by)", {it: "Artisti dell'album (ordinati per)"}],
    ["Album name (sort by)", {it: "Nome dell'album (ordinato per)"}],
    ["Release year", {it: "Anno d'uscita"}],
    ["Disc count", {it: "Numero di dischi"}],
    ["Total tracks count (for disk", {it: "Numero totale di tracce (per il disco"}],
    ["Artist image editor", {it: "Modifica l'immagine dell'artista"}],
    ["Upload a custom artist image by clicking on it, or customize the standard text", {it: "Carica un'immagine dell'artista personalizzata ciccandoci sopra, oppure personalizza il testo di default"}],
    ["Edit", {it: "Modifica"}],
    ["Playlist information", {it: "Informazioni sulla playlist"}],
    ["Name", {it: "Nome"}],
    ["Playlist art", {it: "Immagine della playlist"}],
    ["Upload a custom playlist image by clicking on it, or customize the standard text", {it: "Carica una copertina della playlist personalizzata cliccandoci sopra, oppure personalizza il testo di default"}],
    ["Do you want to delete this playlist? You won't be able to recover it.", {it: "Vuoi eliminare questa playlist? Non potrai recuperarla."}],
    ["Album", {it: "Album"}],
    ["Authors", {it: "Autori"}],
    ["Song authors", {it: "Autori della canzone"}],
    ["Song authors (sort by)", {it: "Autori della canzone (ordinati per)"}],
    ["Composers", {it: "Compositori"}],
    ["Track", {it: "Traccia"}],
    ["Track number", {it: "Numero della traccia"}],
    ["Title", {it: "Titolo"}],
    ["Disk number", {it: "Numero disco"}],
    ["Upload LRC/TTML file", {it: "Carica file LRC/TTML"}],
    ["Albums", {it: "Album"}],
    ["Loading data", {it: "Sto caricando i dati"}],
    ["Artists", {it: "Artisti"}],
    ["Playlists", {it: "Playlist"}],
    ["No playlists were found. You can create one by clicking on the three dots at the right of each track", {it: "Nessuna playlist è stata trovata. Puoi crearne una cliccando sui tre puntini a destra di ogni traccia"}],
    ["Tracks", {it: "Tracce"}],
    ["Edit data", {it: "Modifica dati"}],
    ["CD icon", {it: "Icona del CD"}],
    ["Disk", {it: "Disco"}],
    ["Back button", {it: "Pulsante per tornare indietro"}],
    ["Play and view your local library from your browser", {it: "Ascolta e visualizza la tua libreria locale dal tuo browser"}],
    ["Upload new songs", {it: "Carica nuove canzoni"}],
    ["Change view", {it: "Cambia vista"}],
    ["Application settings", {it: "Impostazioni dell'applicazione"}],
    ["Change library view mode", {it: "Cambia la modalità di visualizzazione della libreria"}],
    ["Album view", {it: "Vista album"}],
    ["Track view", {it: "Vista tracce"}],
    ["Artists view", {it: "Vista artisti"}],
    ["Album artists view", {it: "Vista artisti dell'album"}],
    ["Playlists view", {it: "Vista playlist"}],
    ["Upload new files or folders", {it: "Carica nuovi file o cartelle"}],
    ["Upload new files", {it: "Carica nuovi file"}],
    ["Upload a new folder", {it: "Carica una nuova cartella"}],
    ["Refresh already uploaded folders", {it: "Aggiorna le cartelle già caricate"}],
    ["Your library is empty", {it: "La tua libreria è vuota"}],
    ["Upload some files with the Upload button at the top-right of the screen", {it: "Carica alcuni file con il pulsante nell'angolo in alto a destra dello schermo"}],
    ["A file couldn't be opened", {it: "Non è stato possibile aprire un file"}],
    ["A directory couldn't be opened", {it: "Non è stato possibile aprire una cartella"}],
    ["The appliication couldn't open", {it: "L'applicazione non ha potuto aprire"}],
    ["probably because it was either moved or deleted", {it: "probabilmente visto che è stato spostato o rimosso"}],
    ["Select the file with the button below, or delete it by clicking the three dots at the right of its name in the metadata viewer", {it: "Seleziona il file con il pulsante qui in basso, oppure rimuovilo cliccando sui trei puntini a destra del suo nome nel visualizzatore dei metadati"}],
    ["Select the new directory with the button below, and we'll try to match the files using their file name", {it: "Seleziona la nuova cartella con il pulsante in basso, e cercheremo di trovare i file corripsondenti in base al loro nome"}],
    ["Maybe later", {it: "Magari più tardi"}],
    ["Delete directory files", {it: "Elimina i file della cartella"}],
    ["Pick new file", {it: "Seleziona il nuovo file"}],
    ["Pick new directory", {it: "Seleziona la nuova cartella"}],
    ["Total tracks (for the disk with this track)", {it: "Totale delle tracce (per il disco con questa traccia"}],
    ["Lyrics", {it: "Testi"}],
    ["The application will use", {it: "L'applicazione utilizzerà"}],
    ["no lyrics", {it: "nessun testo"}],
    ["synced lyrics", {it: "testo sincronizzato"}],
    ["plain lyrics", {it: "testo normale"}],
    ["If available, synced lyrics will always be used. However, you can also add plain lyrics by writing them in the text area below", {it: "Se disponibili, i testi sincronizzati verrano sempre utilizzati. Altrimenti, puoi anche aggiungere del testo normale scrivendolo nell'area in basso"}],
    ["Delete synced lyrics", {it: "Elimina testo sincronizzato"}],
    ["Reverse order", {it: "Inverti ordine"}],
    ["Custom colors", {it: "Colori personalizzati"}],
    ["Here you can customize the colors used to generate the stats charts or when no album art is available", {it: "Qui puoi personalizzare i colori utilizzati per generare i grafici delle statistiche, o quando nessuna copertina è disponibile"}],
    ["Delete this color", {it: "Elimina questo colore"}],
    ["Add new color", {it: "Aggiungi nuovo colore"}],
    ["Put the song/artist name below the controls if there's little space", {it: "Inserisci il nome della canzone/artista sotto i controlli se c'è poco spazio"}],
    ["Floating player", {it: "Player fluttuante"}],
    ["No lyrics were uploaded for this track. Do you want to fetch them online? Some metadata will be shared with LRCLib.", {it: "Nessun testo è stato caricato per questa traccia. Vuoi cercarli online? Alcuni metadati verranno condivisi con LRCLib."}],
    ["Delete from queue", {it: "Rimuovi dalla coda"}],
    ["This song has already been added to the playlist. Do you want to add it again?", {it: "Questa canzone è già stata aggiunta alla playlist. Vuoi aggiungerla di nuovo?"}],
    ["Delete playlist", {it: "Rimuovi playlist"}],
    ["Load more items", {it: "Carica più elementi"}],
    ["Pin/unpin playlist", {it: "Fissa (o togli) playlist"}],
    ["Move up", {it: "Sposta in alto"}],
    ["Move down", {it: "Sposta in basso"}],
    ["Search albums", {it: "Cerca album"}],
    ["Search artists", {it: "Cerca artisti"}],
    ["Search album artists", {it: "Cerca artisti dell'album"}],
    ["Search tracks", {it: "Cerca tracce"}],
    ["Search playlists", {it: "Cerca playlist"}],
    ["Artist picture", {it: "Immagine dell'artista"}],
    ["Playlist picture", {it: "Immagine della playlist"}],
    ["Sort by", {it: "Ordina per"}],
    ["Artists name", {it: "Nome degli artisti"}],
    ["Album artists name", {it: "Nome degli artisti degli album"}],
    ["Title name", {it: "Nome del titolo"}],
    ["Custom order", {it: "Ordine personalizzato"}],
    ["Current", {it: "Attuale"}],
    ["Playback rate", {it: "Velocità di riproduzione"}],
    ["Default playback rate", {it: "Velocità di riproduzione predefinita"}],
    ["Adjust the picth to compensate to the new playback rate", {it: "Aggiusta il pitch per compensare la nuova velocità di riproduzione"}],
    ["Change playback speed", {it: "Cambia velocità di riproduzione"}],
    ["Last tip: click on the album art to make the webpage fullscreen. Do the same to exit.", {it: "Ultimo suggerimento: clicca sulla copertina dell'album per rendere la pagina a schermo intero. Fai lo stesso per uscire."}],
    ["Tip: click on the album art of the floating music player to open the main audio player.", {it: "Suggerimento: clicca sulla copertina del player musicale fluttuante per aprire il lettore audio principale."}],
    ["Download song", {it: "Scarica canzone"}],
    ["Export playlist", {it: "Esporta playlist"}],
    ["Playlists successfully imported", {it: "Playlist importate con successo"}],
    ["Import playlist", {it: "Importa playlist"}],
    ["Close the dropdown list", {it: "Chiudi l'elenco a discesa"}],
    ["View on GitHub", {it: "Vedi su GitHub"}],
    ["version", {it: "versione"}],
    ["Information about MusicPlay", {it: "Informazioni su MusicPlay"}],
    ["Do you want to merge all the edited metadata with the output file? This will", {it: "Vuoi unire tutti i metadati modificati con il file di destinazione? Questo"}],
    ["require downloading some libraries (~ 16MB) and will", {it: "richiederà il download di alcune librerie (~ 16MB) e"}],
    ["use more memory. If you don't want to do so, click \"No\" and the original file you've uploaded will be downloaded", {it: "utilizzerà più memoria. Se non vuoi unirli, clicca \"No\" per scaricare il file originale che hai caricato"}],
    ["Export synced lyrics", {it: "Esporta testo sincronizzato"}],
    ["LRC file", {it: "File LRC"}],
    ["TTML file", {it: "File TTML"}],
    ["Selected items", {it: "Elementi selezionati"}],
    ["Discard selection", {it: "Elimina selezione"}],
    ["Options about the selected tracks", {it: "Opzioni sulle tracce selezionate"}],
    ["Select song", {it: "Seleziona canzone"}],
    ["Some of the songs have already been added to the playlist. Do you want to add them again? If you cancel this operation, only the new songs will be added to the playlist.", {it: "Alcune di queste canzoni sono già state aggiunte alla playlist. Vuoi aggiungerle di nuovo? Se annulli, solo le nuove canzoni verranno aggiunte alla playlist."}],
    ["Do you want to delete this track from the application? The file on your device won't be deleted.", {it: "Vuoi eliminare questa traccia dall'applicazione? Il file sul tuo dispositivo non sarà eliminato."}],
    ["Do you want to delete the selected items from the application? The files on your device won't be deleted.", {it: "Vuoi eliminare gli elementi selezionati dall'applicazione? I file sul tuo dispositivo non saranno eliminati."}],
    ["Download tracks", {it: "Scarica tracce"}],
    ["Do you want to enable range select mode? All the songs between the previous click and the next one will be selected. Click again on the icon to deselect all the items in the range. Click again to disable this mode.", {it: "Vuoi abilitare la modalità di selezione di gruppo? Tutte le canzoni presenti tra il clic precedente e quello successivo verranno selezionate. Clicca di nuovo per deselezionare tutte le canzoni nel gruppo cliccato. Clicca ancora per disabilitare."}],
    ["Playlist deletion mode enabled", {it: "Modalità di eliminazione playlist attivata"}],
    ["Disable playlist deletion mode", {it: "Disabilità modalità eliminazione playlist"}],
    ["Do you want to enable playlist range mode deletion? All the songs between the previous click and the next one will be deleted.", {it: "Vuoi abilitare la modalità di eliminazione di gruppo dalla playlist? Tutte le canzoni comprese tra il clic precedente e quello successivo verranno eliminate dalla playlist."}],
    ["Enable/disable playlist range deletion mode", {it: "Abilita/disabilita la modalità di eliminazione di gruppo dalla playlist"}],
    ["Do you want to enable delete mode? All the items you'll click in this playlist will be removed from the playlist. You'll find a pop-up at the bottom of the webpage to exit from this mode.", {it: "Vuoi abilitare la modalità di eliminazione? Tutti gli elementi che cliccherai in questa playlist verranno rimossi dalla playlist."}],
    ["Do you want to delete this playlist", {it: "Vuoi eliminare questa playlist"}],
    ["Gain", {it: "Aumento volume"}],
    ["Stereo output", {it: "Output stereo"}],
    ["Equalizer", {it: "Equalizzatore"}],
    ["Create your own equalizer: pick the range of frequencies to edit and choose the effect to apply", {it: "Crea il tuo equalizzatore: scegli il gruppo di frequenze da modificare e scegli l'effetto da applicare"}],
    ["Enable easy mode", {it: "Abilita modalità semplice"}],
    ["Change the following frequency", {it: "Cambia la frequenza seguente"}],
    ["Decibels increase/decrease", {it: "Aumento/diminuzione dei decibel"}],
    ["From", {it: "Da"}],
    ["To", {it: "A"}],
    ["Effect style", {it: "Stile dell'effetto"}],
    ["Already-added items", {it: "Elementi già aggiunti"}],
    ["Decibels", {it: "Decibel"}],
    ["Crossfade", {it: "Dissolvenza"}],
    ["Transition between tracks (in seconds)", {it: "Transizione tra tracce (in secondi)"}],
    ["Make the transition smoother (non-linear)", {it: "Rendi la transizione più omogenea (non-lineare)"}],
    ["Exponential curve", {it: "Curva esponenziale"}],
    ["Warning", {it: "Attenzione"}],
    ["Due to iOS restrictions, enabling crossfade between tracks require using a different audio decoding method. If you face any issues, disable crossfade. The webpage will be automatically refreshed if you enable/disable crossfade.", {it: "A causa di restrizioni di iOS, l'abilitazione della dissolvenza richiede l'utilizzo di un metodo di decodifica audio differente. Se dovessi avere qualsiasi problema, disabilita la dissolvenza. La pagina viene automaticamente riaggiornata quando viene attivata/disattivata la dissolvenza."}],
    ["Value", {it: "Valore"}],
    ["Reset", {it: "Reimposta"}],
    ["Delete", {it: "Elimina"}],
    ["Add frequency", {it: "Aggiungi frequenza"}],
    ["Enable/disable Picture-in-Picture mode", {it: "Abilita/disabilita modalità Picture-in-Picture"}],
    ["Fetching lyrics of", {it: "Ottengo testo di"}],
    ["on LRCLib", {it: "su LRCLib"}],
    ["Show the shuffle and repeat controls also in the floating player", {it: "Mostra i pulsanti della riproduzione causale e della ripetizione della traccia anche nel player fluttuante"}],
    ["Tip: click on the album art of the Picture-in-Picture player to view the lyrics.", {it: "Suggerimento: clicca sulla copertina del player Picture-in-Picture per visualizzare i testi."}],
    ["Show a pop-up every time a request is made to LRCLib", {it: "Mostra un pop-up ogni volta che una richiesta viene eseguita a LRCLib"}],
    ["Start from a preset", {it: "Inizia da un preset"}],
    ["Pick a preset", {it: "Seleziona un preset"}],
    ["Show less slider controls", {it: "Mostra meno opzioni"}],
    ["Pick a name for the new preset", {it: "Scegli un nome per il nuovo preset"}],
    ["Save as custom preset", {it: "Salva come preset personalizzato"}]
]);

/**
 * Get the translated text of a string
 * @param str the string that should be translated
 * @returns the translated string
 */
export function lang(str: string) {
    const translation = availableTranslations.get(str);
    if (translation) return translation[Settings.language as "it" ?? navigator.language.substring(0, 2) as "it"] ?? str;
    return str;
}