import Settings from "../Settings";

interface TranslationProps {
    it: string,
    customReturn?: string
} 

const availableTranslations = new Map<string, TranslationProps>([
    ["Album art", {it: "Copertina dell'album"}],
    ["Enable/disable shuffle", {it: "Abilita/disabilita riproduzione casuale"}],
    ["Play/pause", {it: "Riproduci/metti in pausa"}],
    ["Next track", {it: "Prossima traccia"}],
    ["Toggle between loop options", {it: "Cambia tra le opzioni di ripetizione"}],
    ["Show/hide lyrics", {it: "Mostra/nascondi testo"}],
    ["Show/hide queue", {it: "Mostra/nascondi coda"}],
    ["Enable/disable sleep timer", {it: "Abilita/disabilita timer pausa"}],
    ["Sync text to timestamp", {it: "Sincronizza testo alla riproduzione"}],
    ["Previous track", {it: "Traccia precedente"}],
    ["No track is being played", {it: "Nessuna traccia è in riproduzione"}],
    ["Track information will appear here", {it: "Le informazioni sulla traccia appariranno qui"}],
    ["Queue", {it: "Coda"}],
    ["Added by the user", {it: "Aggiunto dall'utente"}],
    ["Playing next", {it: "In coda"}],
    ["Sleep timer", {it: "Timer pausa"}],
    ["Timer running", {it: "Timer in esecuzione"}],
    ["Hours", {it: "Ore"}],
    ["Minutes", {it: "Minuti"}],
    ["Seconds", {it: "Secondi"}],
    ["Wait the end of the song before pausing the track", {it: "Attendi la fine della canzone prima di mettere in pausa la traccia"}],
    ["Close", {it: "Chiudi"}],
    ["Disable", {it: "Disabilita"}],
    ["Start", {it: "Avvia"}],
    ["hour", {it: "ora"}],
    ["hours", {it: "ore"}],
    ["minute", {it: "minuto"}],
    ["minutes", {it: "minuti"}],
    ["seconds", {it: "secondi"}],
    ["second", {it: "secondo"}],
    ["remaining", {it: "rimanenti"}],
    ["Playback will be paused at the end of this song", {it: "La riproduzione verrà messa in pausa alla fine di questa canzone."}],
    ["Close settings dialog", {it: "Chiudi dialogo delle impostazioni"}],
    ["Settings", {it: "Impostazioni"}],
    ["Lyrics integration", {it: "Integrazione coi testi"}],
    ["The application can automatically fetch missing lyrics from", {it: "L'applicazione può automaticamente ottenere i testi mancanti da"}],
    ["The application will only share the necessary metadata to identify the currently-playing song. If you enable this, you're also subject to LRCLib's Terms of Service", {it: "L'applicazione condividerà solamente i metadati necessari per identificare la canzone in riproduzione. Se abiliti questo, accetti i termini di servizio di LRCLib"}],
    ["Automatically fetch lyrics if missing", {it: "Ottieni automaticamente i testi se mancanti"}],
    ["Automatically fetch lyrics if the uploaded ones aren't synced", {it: "Ottieni automaticamente i testi se quelli forniti non sono sincronizzati"}],
    ["Browser buttons behavior", {it: "Comportamento dei pulsanti nel browser"}],
    ["You can control the behavior of the media buttons you can find in the Control Center while playing music", {it: "Puoi controllare il comportamento dei pulsanti multimediali che puoi trovare nel Centro di Controllo mentre ascolti la musica"}],
    ["When clicking on the next/previous song button", {it: "Quando clicchi sul pulsante per la prossima/precedente canzone"}],
    ["Skip to the next/previous track", {it: "Passa alla prossima/precedente canzone"}],
    ["Go forwards/backwards in the track", {it: "Vai più avanti/indietro nella traccia"}],
    ["When clicking on the go forwards/backwards button", {it: "Quando clicchi sul pulsante per andare avanti/indietro nella traccia"}],
    ["When using the go forwards/backwards button, always skip of", {it: "Quando usi il pulsante per andare avanti/indietro nella traccia, salta sempre"}],
    ["Application theme", {it: "Tema dell'applicazione"}],
    ["Here you can change all the colors and values used by the application. You can also customize the font and the CSS blur styling. Note that, if the font you've put doesn't load, you might need to disable your browser's privacy protection. The sliders below the color inputs permit to change the opacity of the property", {it: "Qui puoi cambiare tutti i colori ed i valori utilizzati dall'applicazione. Puoi anche personalizzare il font ed il codice CSS della sfumatura. Nota che, se il font che hai messo non carica, potresti dover disattivare le protezioni per la privacy del tuo browser. Gli slider in basso ai selettori colore permettono di regolare l'opacità della proprietà"}],
    ["Background color", {it: "Colore di sfondo"}],
    ["Text/icon color", {it: "Colore del testo/icone"}],
    ["Secondary text color", {it: "Colore del testo secondario"}],
    ["Previous lyrics color (for word-by-word lyrics)", {it: "Colore del testo precedente (per i testi parola-per-parola)"}],
    ["Main card color", {it: "Colore della card principale"}],
    ["Secondary card color", {it: "Colore della card secondaria"}],
    ["Accent color", {it: "Colore accent"}],
    ["Color around the album art", {it: "Colore attorno alla copertina dell'album"}],
    ["CSS font name", {it: "Nome del font CSS"}],
    ["CSS filter for the background album art", {it: "Filtro CSS per la copertina di sfondo"}],
    ["CSS filter for the box-shadow around album arts", {it: "Filtro CSS per la box-shadow attorno alla copertina dell'album"}],
    ["Application size", {it: "Peso dell'applicazione"}],
    ["The application is using", {it: "L'applicazione sta usando"}],
    ["If you're running low on memory, you can use the following buttons to save space. Note that the website will automatically refresh at the end of the process", {it: "Se hai quasi esaurito lo spazio, puoi usare i seguenti pulsanti per salvare spazio. Nota che il sito si aggionerà automaticamente alla fine del processo"}],
    ["Delete all album arts", {it: "Elimina tutte le copertine dell'album"}],
    ["Delete all artist images", {it: "Elimina tutte le immagini degli artisti"}],
    ["Delete all playlist images", {it: "Elimina tutte le immagini delle playlist"}],
    ["Delete all song stats", {it: "Elimina tutte le statistiche sulle canzoni"}],
    ["Delete everything", {it: "Elimina tutto"}],
    ["Close stats dialog", {it: "Chiudi dialogo delle statistiche"}],
    ["Stats about", {it: "Statistiche su"}],
    ["You've listened to", {it: "Hai ascoltato a"}],
    ["aproximately", {it: "approssimatamente"}],
    ["time", {it: "volta"}],
    ["times", {it: "volte"}],
    ["for a total of", {it: "per un totale di"}],
    ["and", {it: "e"}],
    ["When you've listened to", {it: "Quando hai ascoltato"}],
    ["Show the", {it: "Mostra"}],
    ["hours of the day", {it: "le ore del giorno"}],
    ["days of the week", {it: "i giorni della settimana"}],
    ["days of the month", {it: "i giorni del mese"}],
    ["months of the year", {it: "i mesi dell'anno"}],
    ["years", {it: "gli anni"}],
    ["Chart type", {it: "Tipo di grafico"}],
    ["Bar", {it: "Barre"}],
    ["Doughnut", {it: "Ciambella"}],
    ["Line", {it: "Linea"}],
    ["Polar area", {it: "Area polare"}],
    ["Show empty columns", {it: "Mostra le colonne vuote"}],
    ["Data unit: seconds", {it: "Unità dei dati: secondi"}],
    ["Download chart", {it: "Scarica grafico"}],
    ["Export stats", {it: "Esporta statistiche"}],
    ["Expand item", {it: "Espandi elemento"}],
    ["Options about this specific track", {it: "Opzioni su questa specifica traccia"}],
    ["Add to queue", {it: "Aggiungi alla coda"}],
    ["Add to playlist", {it: "Aggiungi alla playlist"}],
    ["Create new playlist", {it: "Crea una nuova playlist"}],
    ["Remove from playlist", {it: "Rimuovi dalla playlist"}],
    ["Delete track", {it: "Elimina traccia"}],
    ["Edit metadata", {it: "Modifica metadati"}],
    ["View stats", {it: "Visualizza statistiche"}],
    ["Pick a name for the new playlist.", {it: "Scegli un nome per la nuova playlist"}],
    ["Text options", {it: "Opzioni del testo"}],
    ["Text", {it: "Testo"}],
    ["Font size", {it: "Dimensione del font"}],
    ["Font used", {it: "Font utilizzato"}],
    ["Background color", {it: "Colore di sfondo"}],
    ["Text color", {it: "Colore del testo"}],
    ["Click here to upload a custom picture", {it: "Clicca qui per caricare un'immagine personalizzata"}],
    ["Save edits", {it: "Salva modifiche"}],
    ["Close without saving", {it: "Chiudi senza salvare"}],
    ["Edit the metadata of", {it: "Modifica i metadati di"}],
    ["Album art options", {it: "Opzioni sulla copertina"}],
    ["Click on the album art to upload a custom image, or change the default text with the options below", {it: "Clicca sulla copertina per caricare un'immagine personalizzata, oppure cambia il testo di default con le opzioni in basso"}],
    ["Other album information", {it: "Altre informazioni sull'album"}],
    ["Album name", {it: "Nome dell'album"}],
    ["Album artists", {it: "Artisti dell'album"}],
    ["Album artists (sort by)", {it: "Artisti dell'album (ordinati per)"}],
    ["Album name (sort by)", {it: "Nome dell'album (ordinato per)"}],
    ["Release year", {it: "Anno d'uscita"}],
    ["Disc count", {it: "Numero di dischi"}],
    ["Total tracks count (for disk", {it: "Numero totale di tracce (per il disco"}],
    ["Artist image editor", {it: "Modifica l'immagine dell'artista"}],
    ["Upload a custom artist image by clicking on it, or customize the standard text", {it: "Carica un'immagine dell'artista personalizzata ciccandoci sopra, oppure personalizza il testo di default"}],
    ["Edit", {it: "Modifica"}],
    ["Playlist information", {it: "Informazioni sulla playlist"}],
    ["Name", {it: "Nome"}],
    ["Playlist art", {it: "Immagine della playlist"}],
    ["Upload a custom playlist image by clicking on it, or customize the standard text", {it: "Carica una copertina della playlist personalizzata cliccandoci sopra, oppure personalizza il testo di default"}],
    ["Do you want to delete this playlist? You won't be able to recover it.", {it: "Vuoi eliminare questa playlist? Non potrai recuperarla."}],
    ["Album", {it: "Album"}],
    ["Authors", {it: "Autori"}],
    ["Song authors", {it: "Autori della canzone"}],
    ["Song authors (sort by)", {it: "Autori della canzone (ordinati per)"}],
    ["Composers", {it: "Compositori"}],
    ["Track", {it: "Traccia"}],
    ["Track number", {it: "Numero della traccia"}],
    ["Title", {it: "Titolo"}],
    ["Disk number", {it: "Numero disco"}],
    ["Upload LRC/TTML file", {it: "Carica file LRC/TTML"}],
    ["Albums", {it: "Album"}],
    ["Loading data", {it: "Sto caricando i dati"}],
    ["Artists", {it: "Artisti"}],
    ["Playlists", {it: "Playlist"}],
    ["No playlists were found. You can create one by clicking on the three dots at the right of each track", {it: "Nessuna playlist è stata trovata. Puoi crearne una cliccando sui tre puntini a destra di ogni traccia"}],
    ["Tracks", {it: "Tracce"}],
    ["Edit data", {it: "Modifica dati"}],
    ["CD icon", {it: "Icona del CD"}],
    ["Disk", {it: "Disco"}],
    ["Back button", {it: "Pulsante per tornare indietro"}],
    ["Play and view your local library from your browser", {it: "Ascolta e visualizza la tua libreria locale dal tuo browser"}],
    ["Upload new songs", {it: "Carica nuove canzoni"}],
    ["Change view", {it: "Cambia vista"}],
    ["Application settings", {it: "Impostazioni dell'applicazione"}],
    ["Change library view mode", {it: "Cambia la modalità di visualizzazione della libreria"}],
    ["Album view", {it: "Vista album"}],
    ["Track view", {it: "Vista tracce"}],
    ["Artists view", {it: "Vista artisti"}],
    ["Album artists view", {it: "Vista artisti dell'album"}],
    ["Playlists view", {it: "Vista playlist"}],
    ["Upload new files or folders", {it: "Carica nuovi file o cartelle"}],
    ["Upload new files", {it: "Carica nuovi file"}],
    ["Upload a new folder", {it: "Carica una nuova cartella"}],
    ["Refresh already uploaded folders", {it: "Aggiorna le cartelle già caricate"}],
    ["Your library is empty", {it: "La tua libreria è vuota"}],
    ["Upload some files with the Upload button at the top-right of the screen", {it: "Carica alcuni file con il pulsante nell'angolo in alto a destra dello schermo"}],
    ["A file couldn't be opened", {it: "Non è stato possibile aprire un file"}],
    ["A directory couldn't be opened", {it: "Non è stato possibile aprire una cartella"}],
    ["The appliication couldn't open", {it: "L'applicazione non ha potuto aprire"}],
    ["probably because it was either moved or deleted", {it: "probabilmente visto che è stato spostato o rimosso"}],
    ["Select the file with the button below, or delete it by clicking the three dots at the right of its name in the metadata viewer", {it: "Seleziona il file con il pulsante qui in basso, oppure rimuovilo cliccando sui trei puntini a destra del suo nome nel visualizzatore dei metadati"}],
    ["Select the new directory with the button below, and we'll try to match the files using their file name", {it: "Seleziona la nuova cartella con il pulsante in basso, e cercheremo di trovare i file corripsondenti in base al loro nome"}],
    ["Maybe later", {it: "Magari più tardi"}],
    ["Delete directory files", {it: "Elimina i file della cartella"}],
    ["Pick new file", {it: "Seleziona il nuovo file"}],
    ["Pick new directory", {it: "Seleziona la nuova cartella"}],
    ["Total tracks (for the disk with this track)", {it: "Totale delle tracce (per il disco con questa traccia"}],
    ["Lyrics", {it: "Testi"}],
    ["The application will use", {it: "L'applicazione utilizzerà"}],
    ["no lyrics", {it: "nessun testo"}],
    ["synced lyrics", {it: "testo sincronizzato"}],
    ["plain lyrics", {it: "testo normale"}],
    ["If available, synced lyrics will always be used. However, you can also add plain lyrics by writing them in the text area below", {it: "Se disponibili, i testi sincronizzati verrano sempre utilizzati. Altrimenti, puoi anche aggiungere del testo normale scrivendolo nell'area in basso"}],
    ["Delete synced lyrics", {it: "Elimina testo sincronizzato"}],
    ["Reverse order", {it: "Inverti ordine"}],
    ["Custom colors", {it: "Colori personalizzati"}],
    ["Here you can customize the colors used when no album art is available", {it: "Qui puoi personalizzare i colori utilizzati quando nessuna copertina è disponibile"}],
    ["Delete this color", {it: "Elimina questo colore"}],
    ["Add new color", {it: "Aggiungi nuovo colore"}],
    ["Put the song/artist name below the controls if there's little space", {it: "Inserisci il nome della canzone/artista sotto i controlli se c'è poco spazio"}],
    ["Floating player", {it: "Player fluttuante"}],
    ["No lyrics were uploaded for this track. Do you want to fetch them online? Some metadata will be shared with LRCLib.", {it: "Nessun testo è stato caricato per questa traccia. Vuoi cercarli online? Alcuni metadati verranno condivisi con LRCLib."}],
    ["Delete from queue", {it: "Rimuovi dalla coda"}],
    ["This song has already been added to the playlist. Do you want to add it again?", {it: "Questa canzone è già stata aggiunta alla playlist. Vuoi aggiungerla di nuovo?"}],
    ["Delete playlist", {it: "Rimuovi playlist"}],
    ["Load more items", {it: "Carica più elementi"}],
    ["Pin/unpin playlist", {it: "Fissa (o togli) playlist"}],
    ["Move up", {it: "Sposta in alto"}],
    ["Move down", {it: "Sposta in basso"}],
    ["Search albums", {it: "Cerca album"}],
    ["Search artists", {it: "Cerca artisti"}],
    ["Search album artists", {it: "Cerca artisti dell'album"}],
    ["Search tracks", {it: "Cerca tracce"}],
    ["Search playlists", {it: "Cerca playlist"}],
    ["Artist picture", {it: "Immagine dell'artista"}],
    ["Playlist picture", {it: "Immagine della playlist"}],
    ["Sort by", {it: "Ordina per"}],
    ["Artists name", {it: "Nome degli artisti"}],
    ["Album artists name", {it: "Nome degli artisti degli album"}],
    ["Title name", {it: "Nome del titolo"}],
    ["Custom order", {it: "Ordine personalizzato"}],
    ["Current", {it: "Attuale"}],
    ["Playback rate", {it: "Velocità di riproduzione"}],
    ["Default playback rate", {it: "Velocità di riproduzione predefinita"}],
    ["Adjust the picth to compensate to the new playback rate", {it: "Aggiusta il pitch per compensare la nuova velocità di riproduzione"}],
    ["Change playback speed", {it: "Cambia velocità di riproduzione"}],
    ["Last tip: click on the album art to make the webpage fullscreen. Do the same to exit.", {it: "Ultimo suggerimento: clicca sulla copertina dell'album per rendere la pagina a schermo intero. Fai lo stesso per uscire."}],
    ["Tip: click on the album art of the floating music player to open the main audio player.", {it: "Suggerimento: clicca sulla copertina del player musicale fluttuante per aprire il lettore audio principale."}],
    ["Download song", {it: "Scarica canzone"}],
    ["Export playlist", {it: "Esporta playlist"}],
    ["Playlists successfully imported", {it: "Playlist importate con successo"}],
    ["Import playlist", {it: "Importa playlist"}],
    ["Close the dropdown list", {it: "Chiudi l'elenco a discesa"}],
    ["View on GitHub", {it: "Vedi su GitHub"}],
    ["version", {it: "versione"}],
    ["Information about MusicPlay", {it: "Informazioni su MusicPlay"}],
    ["Do you want to merge all the edited metadata with the output file? This will", {it: "Vuoi unire tutti i metadati modificati con il file di destinazione? Questo"}],
    ["require downloading some libraries (~ 16MB) and will", {it: "richiederà il download di alcune librerie (~ 16MB) e"}],
    ["use more memory. If you don't want to do so, click \"No\" and the original file you've uploaded will be downloaded", {it: "utilizzerà più memoria. Se non vuoi unirli, clicca \"No\" per scaricare il file originale che hai caricato"}],
    ["Export synced lyrics", {it: "Esporta testo sincronizzato"}],
    ["LRC file", {it: "File LRC"}],
    ["TTML file", {it: "File TTML"}],
    ["Selected items", {it: "Elementi selezionati"}],
    ["Discard selection", {it: "Elimina selezione"}],
    ["Options about the selected tracks", {it: "Opzioni sulle tracce selezionate"}],
    ["Select song", {it: "Seleziona canzone"}],
    ["Some of the songs have already been added to the playlist. Do you want to add them again? If you cancel this operation, only the new songs will be added to the playlist.", {it: "Alcune di queste canzoni sono già state aggiunte alla playlist. Vuoi aggiungerle di nuovo? Se annulli, solo le nuove canzoni verranno aggiunte alla playlist."}],
    ["Do you want to delete this track from the application? The file on your device won't be deleted.", {it: "Vuoi eliminare questa traccia dall'applicazione? Il file sul tuo dispositivo non sarà eliminato."}],
    ["Do you want to delete the selected items from the application? The files on your device won't be deleted.", {it: "Vuoi eliminare gli elementi selezionati dall'applicazione? I file sul tuo dispositivo non saranno eliminati."}],
    ["Download tracks", {it: "Scarica tracce"}],
    ["Do you want to enable range select mode? All the songs between the previous click and the next one will be selected. Click again on the icon to deselect all the items in the range. Click again to disable this mode.", {it: "Vuoi abilitare la modalità di selezione di gruppo? Tutte le canzoni presenti tra il clic precedente e quello successivo verranno selezionate. Clicca di nuovo per deselezionare tutte le canzoni nel gruppo cliccato. Clicca ancora per disabilitare."}],
    ["Playlist deletion mode enabled", {it: "Modalità di eliminazione playlist attivata"}],
    ["Disable playlist deletion mode", {it: "Disabilità modalità eliminazione playlist"}],
    ["Do you want to enable playlist range mode deletion? All the songs between the previous click and the next one will be deleted.", {it: "Vuoi abilitare la modalità di eliminazione di gruppo dalla playlist? Tutte le canzoni comprese tra il clic precedente e quello successivo verranno eliminate dalla playlist."}],
    ["Enable/disable playlist range deletion mode", {it: "Abilita/disabilita la modalità di eliminazione di gruppo dalla playlist"}],
    ["Do you want to enable delete mode? All the items you'll click in this playlist will be removed from the playlist. You'll find a pop-up at the bottom of the webpage to exit from this mode.", {it: "Vuoi abilitare la modalità di eliminazione? Tutti gli elementi che cliccherai in questa playlist verranno rimossi dalla playlist."}],
    ["Do you want to delete this playlist", {it: "Vuoi eliminare questa playlist"}],
    ["Gain", {it: "Aumento volume"}],
    ["Stereo output", {it: "Output stereo"}],
    ["Equalizer", {it: "Equalizzatore"}],
    ["Create your own equalizer: pick the range of frequencies to edit and choose the effect to apply", {it: "Crea il tuo equalizzatore: scegli il gruppo di frequenze da modificare e scegli l'effetto da applicare"}],
    ["Enable easy mode", {it: "Abilita modalità semplice"}],
    ["Change the following frequency", {it: "Cambia la frequenza seguente"}],
    ["Decibels increase/decrease", {it: "Aumento/diminuzione dei decibel"}],
    ["From", {it: "Da"}],
    ["To", {it: "A"}],
    ["Effect style", {it: "Stile dell'effetto"}],
    ["Already-added items", {it: "Elementi già aggiunti"}],
    ["Decibels", {it: "Decibel"}],
    ["Crossfade", {it: "Dissolvenza"}],
    ["Transition between tracks (in seconds)", {it: "Transizione tra tracce (in secondi)"}],
    ["Make the transition smoother (non-linear)", {it: "Rendi la transizione più omogenea (non-lineare)"}],
    ["Exponential curve", {it: "Curva esponenziale"}],
    ["Warning", {it: "Attenzione"}],
    ["Due to iOS restrictions, enabling crossfade between tracks require using a different audio decoding method. If you face any issues, disable crossfade. The webpage will be automatically refreshed if you enable/disable crossfade.", {it: "A causa di restrizioni di iOS, l'abilitazione della dissolvenza richiede l'utilizzo di un metodo di decodifica audio differente. Se dovessi avere qualsiasi problema, disabilita la dissolvenza. La pagina viene automaticamente riaggiornata quando viene attivata/disattivata la dissolvenza."}],
    ["Value", {it: "Valore"}],
    ["Reset", {it: "Reimposta"}],
    ["Delete", {it: "Elimina"}],
    ["Add frequency", {it: "Aggiungi frequenza"}],
    ["Enable/disable Picture-in-Picture mode", {it: "Abilita/disabilita modalità Picture-in-Picture"}],
    ["Fetching lyrics of", {it: "Ottengo testo di"}],
    ["on LRCLib", {it: "su LRCLib"}],
    ["Show the shuffle and repeat controls also in the floating player", {it: "Mostra i pulsanti della riproduzione causale e della ripetizione della traccia anche nel player fluttuante"}],
    ["Tip: click on the album art of the Picture-in-Picture player to view the lyrics.", {it: "Suggerimento: clicca sulla copertina del player Picture-in-Picture per visualizzare i testi."}],
    ["Show a pop-up every time a request is made to LRCLib", {it: "Mostra un pop-up ogni volta che una richiesta viene eseguita a LRCLib"}],
    ["Start from a preset", {it: "Inizia da un preset"}],
    ["Pick a preset", {it: "Seleziona un preset"}],
    ["Show less slider controls", {it: "Mostra meno opzioni"}],
    ["Pick a name for the new preset", {it: "Scegli un nome per il nuovo preset"}],
    ["Save as custom preset", {it: "Salva come preset personalizzato"}],
    ["Avoid copying the audio file in the database if possible. If enabled, the browser might ask you the permission before playing an audio file.", {it: "Evita di copiare il file audio nel database se possibile. Se quest'opzione è abilitata, il browser potrebbe chiedere l'autorizzazione prima di riprodurre un file."}],
    ["Close convert dialog", {it: "Chiudi il dialogo di conversione"}],
    ["Convert music files", {it: "Converti file musicali"}],
    ["You can reduce the music file size by using a different codec or by reducing their bitrate. This might decrease output audio quality", {it: "Puoi ridurre la dimensione del file musicale utilizzando un codec differente oppure riducendo il loro bitrate. Questo potrebbe ridurre la qualità dell'audio"}],
    ["Output audio format", {it: "Formato audio di destinazione"}],
    ["Output quality", {it: "Qualità di destinazione"}],
    ["Pick with a slider", {it: "Seleziona con uno slider"}],
    ["Output quality (from worst to best)", {it: "Qualità di destinazione (dal peggiore al migliore)"}],
    ["Output bitrate (in kbit/s)", {it: "Bitrate di destinazione (in kbit/s)"}],
    ["Increase the output volume of (in decibels)", {it: "Aumenta il volume di (in decibel)"}],
    ["File exportation option", {it: "Opzioni per l'esportazione del file"}],
    ["Replace the currently-saved file with the new one", {it: "Sostituisci il file già salvato con il nuovo"}],
    ["Download the new file", {it: "Scarica il nuovo file"}],
    ["Copy the metadata to the new file", {it: "Copia i metadati nel nuovo file"}],
    ["Convert", {it: "Converti"}],
    ["Converting", {it: "Converto"}],
    ["Artist separation", {it: "Separazione degli artisti"}],
    ["Add the dividers used to separate artists in the metadata", {it: "Aggiungi i divisori utilizzati per separare gli artisti nei metadati"}],
    ["New artist separator", {it: "Nuovo separatore degli artisti"}],
    ["Added separators (click to remove)", {it: "Separatori aggiunti (clicca per rimuovere)"}],
    ["New album artist separator", {it: "Nuovo separatore degli artisti dell'album"}],
    ["Convert tracks", {it: "Converti tracce"}],
    ["Convert song", {it: "Converti canzone"}],
    ["Tip", {it: "Suggerimento"}],
    [`If you've added multiple artists in the same artist tag, you can divide them by specifying the divider symbol (for example a comma) in the settings (under the "Artist separation" tab)`, {it: `Se hai aggiunto più artisti nello stesso metadato, puoi dividerli specificando il loro simbolo di divisione (per esempio una virgola) nelle impostazioni (sotto la voce "Separazione degli artisti")`}],
    ["Metadata copy", {it: "Copia dei metadati"}],
    ["The following settings will be applied when an audio file is exported and the user asks to copy the metadata to the output file", {it: "Le seguenti impostazioni saranno applicate quando un file audio viene esportato e l'utente chiede di copiare i metadati sul file di destinazione"}],
    ["Add timestamps to embedded lyrics", {it: "Aggiungi un timestamp nel campo dei testi"}],
    ["Delete all the metadata that was previously added", {it: "Elimina tutti i metadati che erano stati aggiunti precedentemente"}],
    ["Lyrics language (for MP3 files)", {it: "Lingua dei testi (per i file MP3)"}],
    ["Stats view",{it: "Vista statistiche"}],
    ["Save image", {it: "Salva immagine"}],
    ["Share image", {it: "Condividi immagine"}],
    ["Close image export dialog", {it: "Chiudi dialogo di esportazione dell'immagine"}],
    ["Export your podium", {it: "Esporta il tuo podio"}],
    ["Add fourth and fifth song if available", {it: "Aggiungi quarta e quinta canzone se disponibile"}],
    ["Main text color", {it: "Colore del testo principale"}],
    ["Secondary text color", {it: "Colore del testo secondario"}],
    ["Podium color for first/second/third place", {it: "Colore del podio per il primo/secondo/terzo posto"}],
    ["Podium text color for first/second/third place", {it: "Colore del testo del podio per il primo/secondo/terzo posto"}],
    ["Album art colors", {it: "Colori per le copertine dell'album"}],
    ["Here you can customize the colors used to generate the stats charts", {it: "Qui puoi personalizzare i colori utilizzati per generare i grafici delle statistiche"}],
    ["Show data about", {it: "Mostra dati di"}],
    ["all time", {it: "sempre"}],
    ["this week", {it: "questa settimana"}],
    ["this month", {it: "questo mese"}],
    ["this year", {it: "questo anno"}],
    ["custom", {it: "personalizzato"}],
    ["from", {it: "da"}],
    ["to", {it: "a"}],
    ["Listens of", {it: "Ascolti di"}],
    ["divided by", {it: "divisi per"}],
    ["divided by S", {it: "diviso per", customReturn: "divided by"}],
    ["days of the month", {it: "giorno del mese"}],
    ["Listened for", {it: "Ascoltato per"}],
    ["Your podium", {it: "Il tuo podio"}],
    ["Export and/or share", {it: "Esporta e/o condividi"}],
    ["Stats of", {it: "Statistiche di"}],
    ["Reading all the stats of your entire library, please wait a little", {it: "Sto leggendo tutte le statistiche dell'intera libreria musicale, per favore aspetta un po'"}],
    ["You've listened", {it: "Hai ascoltato"}],
    ["of songs during this time range", {it: "di canzoni in questo lasso di tempo"}],
    ["Your top songs", {it: "Le tue canzoni preferite"}],
    ["These have been your most listened songs for the selected time range", {it: "Queste sono le tue canzoni più ascoltate per il lasso di tempo selezionato"}],
    ["My top songs", {it: "Le mie canzoni più ascoltate"}],
    ["Load all", {it: "Carica tutto"}],
    ["Click on the track's name to see the stats of that track", {it: "Clicca sul nome di ogni traccia per vedere le statistiche di quella traccia"}],
    ["Your music playback, in numbers", {it: "Il tuo ascolto musicale, in numeri"}],
    ["The day of the selected interval you've listened to music the most is", {it: "Il giorno dell'intervallo selezionato in cui hai ascoltato di più la musica è"}],
    ["with", {it: "con"}],
    ["The day", {it: "Il giorno"}],
    ["of the week", {it: "della settimana"}],
    ["you've listened to music the most is", {it: "dove hai ascoltato di più la musica è"}],
    ["Which", {it: "Quale"}],
    ["hour of the day", {it: "ora del giorno"}],
    ["day", {it: "giorno"}],
    ["day of the week", {it: "giorno della settimana"}],
    ["day of the month", {it: "giorno del mese"}],
    ["month", {it: "mese"}],
    ["year", {it: "anno"}],
    ["have you listened to music the most?", {it: "hai ascoltato di più la musica?"}],
    ["Music playback divided by", {it: "Ascolto musicale diviso per"}],
    ["Your favorite artists", {it: "I tuoi artisti preferiti"}],
    ["Your most listened artist is", {it: "L'artista più ascoltato è"}],
    ["with a total of", {it: "con un totale di"}],
    ["Most listened album", {it: "Album più ascoltato"}],
    ["Click on the artist name above to see all the stats of that artist", {it: "Clicca sul nome dell'artista per vedere tutte le statistiche di quell'artista"}],
    ["Your top", {it: "I tuoi migliori"}],
    ["artists, divided by", {it: "artisti, divisi per"}],
    ["Top", {it: "Migliori"}],
    ["artists divided by", {it: "artisti divisi per"}],
    ["Your favorite albums", {it: "I tuoi album preferiti"}],
    ["Your most listened album is", {it: "Il tuo album più ascoltato è"}],
    ["by", {it: "di"}],
    ["Click on the album name above to see all the stats of the songs in that album", {it: "Clicca sul nome dell'album per vedere tutte le statistiche delle canzoni in quell'album"}],
    ["albums, divided by", {it: "album, divisi per"}],
    ["albums divided by", {it: "album divisi per"}],
    ["Stats about", {it: "Statistiche su"}],
    ["Most listened albums", {it: "Album più ascoltati"}],
    ["My top artists", {it: "I miei artisti più ascoltati"}],
    ["My top albums", {it: "I miei album più ascoltati"}],
    ["My top albums of", {it: "I miei album più ascoltati di"}],
    ["Plays divided by album and organized", {it: "Ascolti divisi per album ed organizzati"}],
    ["in the selected time interval", {it: "nel lasso di tempo specificato"}],
    ["by hour", {it: "per ora"}],
    ["by month", {it: "per mese"}],
    ["by year", {it: "per anno"}],
    ["Top albums of", {it: "Migliori album di"}],
    ["My top songs of", {it: "Le mie canzoni più ascoltate di"}],
    ["by day of week", {it: "per giorno della settimana"}],
    ["Top tracks of", {it: "Le mie tracce più ascoltate di"}],
    ["Plays per", {it: "Ascolti per"}],
    ["Plays of", {it: "Ascolti di"}],
    ["days of week", {it: "giorni della settimana"}],
    ["My top tracks of", {it: "Le mie tracce preferite di"}],
    ["Most played songs", {it: "Canzoni più ascoltate"}],
    ["Plays divided by song and organized", {it: "Ascolti divisi per canzone ed organizzati"}],
    ["only tracks with", {it: "solo tracce con"}],
    ["day of week", {it: "giorno della settimana"}],
    ["month", {it: "mese"}],
    ["divided by F", {it: "divise per", customReturn: "divided by"}], // Female version of the "Divided by" string
    ["week", {it: "settimana"}],
    ["Chart export options", {it: "Opzioni di esportazione del grafico"}],
    ["Chart text color", {it: "Colore del testo secondario"}],
    ["Grid lines color", {it: "Colore delle linee degli assi"}],
    ["You can customize the chart colors from the Settings", {it: "Puoi personalizzare i colori del grafico dalle impostazioni"}],
    ["all time", {it: "da sempre"}],
    ["albums, organized", {it: "album, organizzati"}],
    ["albums of", {it: "album di"}],
    ["Most listened tracks", {it: "Tracce più ascoltate"}],
    ["tracks, organized", {it: "tracce, organizzate"}],
    ["tracks of", {it: "tracce di"}],
    ["Music playback", {it: "Ascolto musicale"}],
    ["artists", {it: "artisti"}],
    ["albums", {it: "album"}],
    ["Album artist", {it: "Artista dell'album"}],
    ["Playlist", {it: "Playlist"}],
    ["Artist", {it: "Artista"}],
    ["Home view", {it: "Vista home"}],
    ["Homepage", {it: "Pagina home"}],
    ["Default page", {it: "Pagina di default"}],
    ["Home", {it: "Home"}],
    ["Change the order of the displayed card on the homepage. Changes will be applied the next time you'll open the Home view", {it: "Cambia l'ordine degli elementi visualizzati nella pagina home. I cambiamenti verranno applicati la prossima volta che aprirai la vista Home"}],
    ["Hide", {it: "Nascondi"}],
    ["Up", {it: "Su"}],
    ["Down", {it: "Giù"}],
    ["Show", {it: "Mostra"}],
    ["Put the recently played elements on one line", {it: "Metti gli elementi più recenti su una linea"}],
    ["Put the displayed cards on the homepage on one line", {it: "Metti gli altri elementi visualizzati sulla homepage in una linea"}],
    ["Maximum number of recently played elements", {it: "Numero massimo di elementi riprodotti di recente"}],
    ["Default", {it: "Predefinito"}],
    ["Without the division", {it: "Senza la divisione"}],
    ["Remove from recently played", {it: "Rimuovi dalle riproduzioni recenti"}],
    ["Scroll for more", {it: "Scorri per vedere di più"}],
    ["You can pin tracks, albums, artists and playlists to the homepage by long pressing them. To move their position, drag and drop them", {it: "Puoi aggiungere tracce, canzoni, album e playlist alla pagina home tenendo premuto su di loro. Per cambiare il loro ordine, trascinali."}],
    ["Disable removing elements by long-pressing them. This should permit you to drag and drop elements also on mobile devices", {it: "Disabilita la rimozione degli elementi tenendo premuto. Questo dovrebbe permetterti di trascinare gli elementi anche sui dispositivi mobili"}],
    ["Without the top number", {it: "Senza il numero di elementi visualizzati"}],
    ["Without the \"Only with\" text", {it: "Senza il testo \"Solo con \""}],
    ["Without the top number and the division", {it: "Senza la divisione ed il numero degli elementi"}],
    ["Without the top number and the \"Only with\" text", {it: "Senza il numero degli elementi ed il testo \"Solo con\""}],
    ["Without the division and the \"Only with\" text", {it: "Senza la divisione ed il testo \"Solo con\""}],
    ["Without the division, top number and the \"Only with\" text", {it: "Senza la divisione, il numero degli elementi ed il testo \"Senza con\""}],
    ["Added to home page", {it: "Aggiunto alla pagina home"}],
    ["Removed from home page", {it: "Rimosso dalla pagina home"}],
    ["Your recent picks", {it: "I tuoi ascolti recenti"}],
    ["Your pinned album artists", {it: "I tuoi artisti dell'album fissati"}],
    ["Your pinned tracks", {it: "Le tue tracce fissate"}],
    ["Your pinned albums", {it: "I tuoi album fissati"}],
    ["Your pinned artists", {it: "I tuoi artisti fissati"}],
    ["Your pinned playlists", {it: "Le tue playlist fissate"}],
    ["Last.fm integration", {it: "Integrazione con last.fm"}],
    ["You can connect MusicPlay to Last.fm so that all your listens will be tracked. You'll need to create a new", {it: "Puoi connettere MusicPlay a Last.fm in modo che tutti i tuoi ascolti saranno tracciati. Dovrai creare un nuovo"}],
    ["API account on last.fm", {it: "account API su last.fm"}],
    ["You can put whatever name you like, then just copy and paste the API key and secret here below", {it: "Puoi inserire qualsiasi nome tu voglia, poi copia ed incolla l'API key ed il secret qui in basso"}],
    ["Connect", {it: "Connetti"}],
    ["Last.fm account connected", {it: "Account last.fm connesso"}],
    ["Disconnect", {it: "Disconnetti"}],
    ["Close alert", {it: "Chiudi avviso"}],
    ["Syncing with Google Drive", {it: "Sincronizzo con Google Drive"}],
    ["Syncing with OneDrive", {it: "Sincronizzo con OneDrive"}],
    ["You need to log in to sync with your cloud service", {it: "Devi accedere per sincronizzare i dati col cloud"}],
    ["Sync", {it: "Sincronizza"}],
    ["Cloud sync", {it: "Sincronizzazione cloud"}],
    ["If you want to change account or provider, you need to disable syncing", {it: "Se vuoi cambiare account o provider, devi disabilitare la sincronizzazione"}],
    ["Disable sync", {it: "Disabilita sincronizzazione"}],
    ["Backup with", {it: "Backup con"}],
    ["You can back up your library on OneDrive. Just log in with your Microsoft account, and we'll take care of the rest", {it: "Puoi eseguire il backup della tua libreria su OneDrive. Accedi con il tuo account Microsoft, e ci occuperemo del resto"}],
    ["Set up", {it: "Configura"}],
    ["You can back up your library on Google Drive", {it: "Puoi eseguire il backup della tua libreria su Google Drive"}],
    ["Easy method", {it: "Metodo semplice"}],
    ["You just need to press the button below. Due to Google's limitations, you'll need to authorize the access to your Google Drive every hour", {it: "Devi solo premere il pulsante in basso. A causa di limitazioni da parte di Google, dovrai autorizzare l'accesso al tuo Google Drive ogni ora"}],
    ["Advanced method (doesn't require authorization every hour)", {it: "Metodo avanzato (non richiede l'autorizzazione ogni ora)"}],
    ["If you want an automatic connection with Google Drive (so that you won't need to authenticate every hour), follow these steps", {it: "Se vuoi una connessione automatica con Google Drive (così da non dover rieseguire l'accesso ogni ora), segui questi passaggi"}],
    ["Click on this link", {it: "Clicca questo collegamento"}],
    [`then click on the "Create" button`, {it: "poi clicca sul pulsante \"Crea\""}],
    [`You'll see a scary webpage. In the top-right corner, you should see a rectangle with the notifications. Click on the "Select project" button of the first notification`, {it: "Vedrai una pagina piena di informazioni. Nell'angolo in alto a destra, dovresti vedere un rettangolo con le notifiche. Clicca sul pulsante \"Seleziona progetto\" della prima notifica"}],
    [`In the middle of the page, you should now see a square titled "API". Click on the "Go to API Overview" button`, {it: `Nel mezzo della pagina, dovresti ora vedere un quadrato intitolato "API". Cicca sul pulsante "Vai alla panoramica API" in quella scheda`}],
    [`Go on the "API library" tab, search "Drive" in the textbox in the middle of the screen, click on the "Google Drive API" result and then click on "Enable"`, {it: `Vai sulla scheda "Libreria", cerca "Drive" nella casella di testo in mezzo allo schermo, clicca sul risultato intitolato "Google Drive API" e poi clicca su "Abilita"`}],
    [`Now, go on the "Credentials" page (you can access it from the left menu, or by clicking on the three lines in the top-left corner if you're on mobile). Click on "Create credentials" and pick "OAuth Client ID"`, {it: `Ora, vai sulla pagina delle "Credenziali" (puoi accederci dal menu a sinistra, oppure cliccando sulle tre linee in alto a sinistra se sei su un dispositivo mobile). Clicca su "Crea credenziali" e scegli "Client ID OAuth"`}],
    [`You'll be asked to set up the consent screen. Click on that button, then on the "Get started" button, and fill the required information. Don't worry, you'll be the only one that'll use the API, so you can put whatever you want`, {it: "Ti verrà chiesto di impostare la schermata di consenso. Clicca su quel pulsante, poi sul pulsante \"Continua\" ed inserisci le informazioni richieste. Non preoccuparti, sarai l'unico che utilizzerà l'API, quindi puoi mettere qualsiasi cosa tu voglia"}],
    [`Let's now go to the "Clients" page you can find in the left menu (just like before, you can access it by clicking the three lines in the top-left corner if you're on mobile). Click "Create client", choose "OAuth Client ID" and "Web application". In the "Authorized JavaScript origins", put`, {it: "Ora vai sulla pagina \"Credenziali\" che puoi trovare sul menu a sinistra (come prima, puoi accederci cliccando le tre linee nell'angolo in alto a sinistra se sei su un dispositivo mobile). Clicca su \"Crea credenziali\", scegli \"Client ID OAuth\" e poi \"Applicazione web\". Nelle \"Origini JavaScript autorizzate\", inserisci"}],
    [`and in the "Authorized redirect URLs" put`, {it: `e negli "URL di reindirizzamento autorizzati" inserisci`}],
    [`Now, click on the "Create" button, and copy the Client ID and the Client Secret below`, {it: "Ora, clicca sul pulsante \"Crea\", e copia il Client ID ed il Client Secret qui in basso"}],
    [`Last step: go on the "Audience" page (always on the left menu), and add the email address of your Google account in the "Test users" section`, {it: "Ultimo passaggio: vai sulla pagina \"Pubblico\" (sempre nel menù a sinistra), ed aggiungi l'email del tuo account nella sezione \"Utenti di prova\""}],
    ["To go back to the easy mode, leave these two fields blank", {it: "Per ritornare alla modalità semplice, lascia questi due campi vuoit"}],
    ["Connect to Google Drive", {it: "Connetti a Google Drive"}],
    ["Change the name of artist number", {it: "Cambia il nome dell'artista numero"}],
    ["Who is singing this", {it: "Chi sta cantando questa"}],
    ["line", {it: "linea"}],
    ["word", {it: "parola"}],
    ["Apply", {it: "Applica"}],
    ["Lyrics with multiple artists", {it: "Testi con più artisti"}],
    ["You can specify which artist is singing which line by long-pressing a line in the Lyrics view. You'll then see the artist name and image.", {it: "Puoi specificare quale artista sta cantando una parte della canzone tenendo premuto su una linea nella vista dei testi. Vedrai poi il nome dell'artista e la sua immagine."}],
    ["Force text alignment", {it: "Forza l'allineamento del testo"}],
    ["Left", {it: "Sinistra"}],
    ["Center", {it: "Centro"}],
    ["Right", {it: "Destra"}]
]);

/**
 * Get the translated text of a string
 * @param str the string that should be translated
 * @returns the translated string
 */
export function lang(str: string) {
    const translation = availableTranslations.get(str);
    if (translation) return translation[Settings.language as "it" ?? navigator.language.substring(0, 2) as "it"] ?? translation.customReturn ?? str;
    return str;
}